### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by jotego** [RobertPeip/PlayStation_MiSTer#2]
It looks like some files are missing for compilation:

![imagen](https://user-images.githubusercontent.com/1863036/142773272-66bb6440-9ae6-4993-9562-d53d4aa84fe0.png)

Could you please add them? 
Thank you

**Comment by RobertPeip** [comment]
The files are checked in (sys folder).
Are you sure you use Quartus 17?

I know of at least 3 people who could build the core as checked in, so I don't know what the reason is...

**Comment by birdybro** [comment]
I was able to build the core just now to test (and multiple commits previously in a row as he's been updating the repo). It took awhile because my computer's slow, but wanted to make sure it works independently of Robert's setup too. 
![gHdUgjVjT0](https://user-images.githubusercontent.com/16388068/142778571-1f0f3f33-b4cc-466d-84bf-a9bcbe4b30f3.png)
Here's the software version and OS I'm using:
* Quartus Prime Standard Edition 17.0.0
* Windows 11 Pro x64

Must be something different about your configuration. @jotego do you use Quartus on Linux? If so maybe there is a case-sensitivity issue happening. Maybe you are trying to port it to your framework? Since these instances are in the MiSTer Framework here --> https://github.com/RobertPeip/PlayStation_MiSTer/tree/main/sys

**Comment by Kitrinx** [comment]
Can confirm, all files are present and builds work fine using Quartus 17.

**Comment by thehughhefner** [comment]
I have the same issue as Jotego

**Comment by jotego** [comment]
@birdybro I'm using the git repository as it is, but I run Quartus 17 (or 20) from linux. So it would be case sensitive for file names.

**Comment by birdybro** [comment]
@jotego Yes it's probably case-sensitivity then without looking at it deeper myself. The errors generated from using version 20 instead of 17 are a little different when I've ran into them, usually just a couple strings in the top-level's QSF that need to be modified since they just changed the name of some of those variables for whatever reason.

**Comment by jotego** [comment]
I can confirm that it works with Quartus 17. I was trying Quartus 20 before. Thanks for your kind replies.
